### ISSUE TITLE
Add this exporter to Minio Cookbook

### ISSUE THREAD

**Issue by nitisht** [joe-pll/minio-exporter#1]
Would it be possible to add this exporter to [Minio Cookbook](https://github.com/minio/cookbook)? It will help community members find this project easily.

**Comment by joe-pll** [comment]
Hi, I added the recipe and create a PR. You can follow the request here https://github.com/minio/cookbook/pull/196

**Comment by nitisht** [comment]
great! Thanks @joe-pll

**Comment by nitisht** [comment]
hi @joe-pll since this project is based on Minio `admin` APIs, just wanted to update you that we're going for a full re-design of these APIs (https://github.com/minio/minio/pull/4826). 

This means there may be changes needed to make `minio-exporter` work properly. Before we take in minio/cookbook#196 just wanted to confirm if you plan to support this project in near future..

**Comment by joe-pll** [comment]
Hi @nitisht, yes, I plan to support this project in the future.

**Comment by nitisht** [comment]
Thanks @joe-pll we took minio/cookbook#196
