### ISSUE TITLE
V0.2.0 on docker hub built with  environment CGOENABLED=1 

### ISSUE THREAD

**Issue by rustup** [joe-pll/minio-exporter#11]
https://hub.docker.com/r/joepll/minio-exporter/ v0.2.0 built with CGOENABLED=1 . 
Busybox doesn't provide system runtime.  minio_exporter crashes.

**Comment by joe-pll** [comment]
I checked and you are right. I fixed the image and add a compatibility table in the REAME. Minio changed the api in the last 15 days. At the moment minio-exporter master with minio latest release is not working.
I'll fix it asap.
