### ISSUE TITLE
was collected before with the same name and label values

### ISSUE THREAD

**Issue by stefanmonkey** [joe-pll/minio-exporter#2]
I have a problem with one minio server with multi export (four export).

```
An error has occurred during metrics collection:

3 error(s) occurred:
* collected metric minio_storage_storage_type label:<name:"type" value:"Erasure" > gauge:<value:2 >  was collected before with the same name and label values
* collected metric minio_storage_storage_type label:<name:"type" value:"Erasure" > gauge:<value:2 >  was collected before with the same name and label values
* collected metric minio_storage_storage_type label:<name:"type" value:"Erasure" > gauge:<value:2 >  was collected before with the same name and label values
```

I check the code.
and 
`func collectStorageInfo` run in for loop `for _, stats := range statsAll` 

last, I just comment the function collectStorageInfo, and exporter run normal.

**Comment by joe-pll** [comment]
Hi, I can't replicate your problem. I started four exporter pointing on the same Minio server and started sampling every 2 seconds on each exporter running for more than 5 minutes. I haven't seen the error. Can you please tell me the version on Minio you are using?

**Comment by stefanmonkey** [comment]
I have four server instance run minio server with 16 disk in test environment.

the start minio server command:
```
/usr/local/minio/bin/minio server http://10.1.61.17/home/minio/export1 http://10.1.61.17/home/minio/export2 http://10.1.61.17/home/minio/export3 http://10.1.61.17/home/minio/export4 http://10.1.61.168/home/minio/export1 http://10.1.61.168/home/minio/export2 http://10.1.61.168/home/minio/export3 http://10.1.61.168/home/minio/export4 http://10.1.61.171/home/minio/export1 http://10.1.61.171/home/minio/export2 http://10.1.61.171/home/minio/export3 http://10.1.61.171/home/minio/export4 http://10.1.61.172/home/minio/export1 http://10.1.61.172/home/minio/export2 http://10.1.61.172/home/minio/export3 http://10.1.61.172/home/mini/export4 -C /usr/local/minio/conf
```

one server with four export 
* /home/minio/export1
* /home/minio/export2
* /home/minio/export3
* /home/minio/export4

minio version:
```
Version: 2017-10-27T18:59:02Z
Release-Tag: RELEASE.2017-10-27T18-59-02Z
Commit-ID: 03df692ae2f911943d5ef98b0ee2f9461605fb8c
```

I think problem is one server with four export, the exporter "storage_type" need one more label to identify.

I create a pr #3

**Comment by joe-pll** [comment]
Hi, sorry for the late answer, I was quite busy last days. I'll try to look at the PR this week.
