### ISSUE TITLE
Not able to compile minio-exporter

### ISSUE THREAD

**Issue by abhinav-chittora** [joe-pll/minio-exporter#6]
While trying to compile using master branch or any other branch, I am getting following error:- 

```
╰─# make                                                                                                                                           
... formatting packages
... getting dependencies
... building binaries
# github.com/minio-exporter
./minio_exporter.go:443: si.Backend.ReadQuorum undefined (type struct { Type madmin.BackendType; OnlineDisks int; OfflineDisks int; StandardSCParity int; RRSCParity int } has no field or method ReadQuorum)
./minio_exporter.go:451: si.Backend.WriteQuorum undefined (type struct { Type madmin.BackendType; OnlineDisks int; OfflineDisks int; StandardSCParity int; RRSCParity int } has no field or method WriteQuorum)
make: *** [build] Error 2

```

Any suggestion? 

**Environment: -** 
```
NAME="CentOS Linux"
VERSION="7 (Core)"
```

**Comment by joe-pll** [comment]
Hi @abhinav-chittora,
sorry about that, the madmin package changed a few days ago and I did not see it. Thanks for the Issue.
The ReadQuorum and the WriteQuorum have been replaced by StandardSCParity and RRSCParity.

Let me know if you have any other issue, otherwise I will close this.

**Comment by abhinav-chittora** [comment]
yes. it worked like charm. Thanks for the quick update. I would like to contribute as well. Is there any pending feature that I can pick to work on?
